// <auto-generated />
using System;
using GestionCalidad.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionCalidad.Migrations
{
    [DbContext(typeof(GestionCalidadContext))]
    partial class GestionCalidadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionCalidad.Dominio.Departamento", b =>
                {
                    b.Property<int>("id_Departamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_Departamento"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_Departamento");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("GestionCalidad.Dominio.InformeCalidad", b =>
                {
                    b.Property<int>("Id_InformeCalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_InformeCalidad"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.HasKey("Id_InformeCalidad");

                    b.ToTable("InformeCalidad");
                });

            modelBuilder.Entity("GestionCalidad.Dominio.InformeCalidad_Departamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("CodigoAtencion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_Departamento")
                        .HasColumnType("integer");

                    b.Property<int>("id_InformeCalidad")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("id_Departamento");

                    b.HasIndex("id_InformeCalidad");

                    b.ToTable("InformeCalidad_Departamento");
                });

            modelBuilder.Entity("GestionCalidad.Dominio.InformeQueja", b =>
                {
                    b.Property<int>("id_InformeQueja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_InformeQueja"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.HasKey("id_InformeQueja");

                    b.ToTable("InformeQueja");
                });

            modelBuilder.Entity("GestionCalidad.Dominio.InformeQueja_Departamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("CodigoPaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_Departamento")
                        .HasColumnType("integer");

                    b.Property<int>("id_InformeQueja")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("id_Departamento");

                    b.HasIndex("id_InformeQueja");

                    b.ToTable("InformeQueja_Departamento");
                });

            modelBuilder.Entity("GestionCalidad.Dominio.InformeCalidad_Departamento", b =>
                {
                    b.HasOne("GestionCalidad.Dominio.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("id_Departamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCalidad.Dominio.InformeCalidad", "InformeCalidad")
                        .WithMany()
                        .HasForeignKey("id_InformeCalidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("InformeCalidad");
                });

            modelBuilder.Entity("GestionCalidad.Dominio.InformeQueja_Departamento", b =>
                {
                    b.HasOne("GestionCalidad.Dominio.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("id_Departamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCalidad.Dominio.InformeQueja", "InformeQueja")
                        .WithMany()
                        .HasForeignKey("id_InformeQueja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("InformeQueja");
                });
#pragma warning restore 612, 618
        }
    }
}
